//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities : DbContext
    {
        public DbCVEntities()
            : base("name=DbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbAbout> TbAbout { get; set; }
        public virtual DbSet<TbAdmin> TbAdmin { get; set; }
        public virtual DbSet<TbContact> TbContact { get; set; }
        public virtual DbSet<TbDocuments> TbDocuments { get; set; }
        public virtual DbSet<TbExperiences> TbExperiences { get; set; }
        public virtual DbSet<TbHobbies> TbHobbies { get; set; }
        public virtual DbSet<TbSocial> TbSocial { get; set; }
        public virtual DbSet<TbTalents> TbTalents { get; set; }
        public virtual DbSet<TbTrainings> TbTrainings { get; set; }
    }
}
