//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbHobbies
    {
        public int Id { get; set; }
        public string Explanation1 { get; set; }
        public string Explanation2 { get; set; }
        public string Photo { get; set; }
    }
}
