//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbTalents
    {
        public int Id { get; set; }
        public string Talent { get; set; }
        public Nullable<byte> Ratio { get; set; }
        public string degree { get; set; }
    }
}
